# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'IPv6Test' do

pod 'AFNetworking',’~>3.0.4’
pod 'SDAutoLayout', '~> 1.50'
pod 'SDWebImage+ExtensionSupport', '~> 3.7.1.2'
pod 'MBProgressHUD','~>0.9.2'
pod 'CocoaAsyncSocket', '~> 7.4.3'

end

target 'IPv6TestTests' do

end

target 'IPv6TestUITests' do

end

